name: Deploy Language content to Pages

on:
  push:
    branches: ["lang"]
  workflow_dispatch:
    inputs:
      generate_sitemap:
        description: 'Whether to generate sitemap.xml'
        required: true
        type: boolean
        default: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    uses: doc2401/actions/.github/workflows/lang-deploy.yml@main
    with:
      generate_sitemap: ${{ github.event_name != 'workflow_dispatch' || inputs.generate_sitemap }}
      config_path: 'lang.json'
